default: dev
workspaces:
  - name: dev
    path: ~/workspace/cmskit
    repositories:
      - name: workspace
        url: git@github.com:cmskitdev/workspace.git
        branch: main
        path: workspace
      - name: common
        url: git@github.com:cmskitdev/common.git
        branch: main
        path: packages/common
      - name: notion
        url: git@github.com:cmskitdev/notion.git
        branch: main
        path: packages/clients/notion
      - name: cli
        url: git@github.com:cmskitdev/cli.git
        branch: main
        path: packages/cli
        runners:
          - cwd: packages/cli
            watch: true
            matchers:
              - include: "**/*.ts"
            commands:
              - name: "dev"
                command:
                  - "npm"
                  - "run"
                  - "dev"
              - name: "build"
                command:
                  - "npm"
                  - "run"
                  - "build"
